# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
     branches: [ master ]
  pull_request:
     branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry pytest
        if [ -f requirements.txt ]; then poetry install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest
